version: '3'
services:
  bind9:
    image: ubuntu/bind9:latest
    container_name: bind9
    environment:
      - BIND9_USER=root
      - TZ=Asia/Jakarta
    ports:
      - 53:53/tcp
      - 53:53/udp
    volumes:
      - ./config:/etc/bind
      - ./cache:/var/cache/bind
      - ./record:/var/lib/bind
    restart: always
